apiVersion: v1
kind: Service
metadata:
  name: maven-service
spec:
  type: NodePort
  ports:
  - name: maven
    port: 19090
    targetPort: 8080
    protocol: TCP
  selector:
    app: maven
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maven-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
        - name: maven
          image: registry-scu.cloudtogo.cn/maven:latest
          ports:
          - containerPort: 8080
          env:
            - name: key
              value: "value"
